// Auto-generated from 2026 NCAA Player draft.xlsx - PICKS tab
export interface Player {
  name: string;
  team: string; // NCAA team name
}

export interface Owner {
  real_name: string;
  team_name: string;
  players: Player[];
}

export const owners: Owner[] = [
  {
    real_name: "Mike",
    team_name: "Joe Mama",
    players: [
      { name: "Boozer", team: "Duke" },
      { name: "Darryn Peterson", team: "Kansas" },
      { name: "Boogie Fland", team: "Florida" },
      { name: "Christian Anderson", team: "Texas Tech" },
      { name: "John Blackwell", team: "Wisconsin" },
      { name: "Melvin Council Jr.", team: "Kansas" },
      { name: "Herni Veesaar", team: "North Carolina" },
      { name: "Bryce Hopkins", team: "St. Johns" },
      { name: "Larry Johnson", team: "McNeese" },
      { name: "Billy Richmond III", team: "Arkansas" },
      { name: "Joshua Dent", team: "Saint Marys" },
      { name: "Oziyah Sellers", team: "St. Johns" },
    ],
  },
  {
    real_name: "Kyle Sherer",
    team_name: "THE Hanover U",
    players: [
      { name: "Brayden Burries", team: "Arizona" },
      { name: "Jeremy Fears", team: "Michigan" },
      { name: "Tamin Lipsey", team: "Iowa" },
      { name: "Kylan Boswell", team: "Illinois" },
      { name: "Andrej Stojakovic", team: "Illinois" },
      { name: "Donovan Atwell", team: "Texas Tech" },
      { name: "Anthony Dell'Orso", team: "Arizona" },
      { name: "Amari Allen", team: "Alabama" },
      { name: "C.J. Cox", team: "Purdue" },
      { name: "Tyler Nickel", team: "Vanderbilt" },
      { name: "Devin Royal", team: "Nebraska" },
      { name: "Nikolas Khamenia", team: "Duke" },
    ],
  },
  {
    real_name: "Brian Baker",
    team_name: "Brian's Team",
    players: [
      { name: "Thomas Haugh", team: "Florida" },
      { name: "Fletcher Loyer", team: "Purdue" },
      { name: "Trey Kaufman-Renn", team: "Purdue" },
      { name: "Tobe Awaka", team: "Arizona" },
      { name: "Meleek Thomas", team: "Arkansas" },
      { name: "Coen Carr", team: "Michigan State" },
      { name: "Duke Miles", team: "Vanderbilt" },
      { name: "Nolan Winter", team: "Wisconsin" },
      { name: "Blake Buchanan", team: "Iowa State" },
      { name: "Joseph Tugler", team: "Houston" },
      { name: "Kur Teng", team: "Michigan State" },
      { name: "Davis Fogle", team: "Gonzaga" },
    ],
  },
  {
    real_name: "Puff",
    team_name: "Puff's Team",
    players: [
      { name: "Yaxel Lendeborg", team: "Michigan" },
      { name: "Solo Ball", team: "UConn" },
      { name: "Xaivian Lee", team: "Florida" },
      { name: "Jaxon Kohler", team: "Michigan State" },
      { name: "Milos Uzan", team: "Houston" },
      { name: "Malik Thomas", team: "Virginia" },
      { name: "Jeremiah Wilkinson", team: "Georgia" },
      { name: "John Mobley Jr.", team: "Ohio State" },
      { name: "Devin Royal", team: "Ohio State" },
      { name: "Tavari Johnson", team: "Akron" },
      { name: "Mason Falslev", team: "Utah State" },
      { name: "Chance Mallory", team: "Virginia" },
    ],
  },
  {
    real_name: "Tim",
    team_name: "JustBeatDan",
    players: [
      { name: "Graham Ike", team: "Gonzaga" },
      { name: "Milan Momcilovic", team: "Iowa State" },
      { name: "AJ Dybansta", team: "BYU" },
      { name: "Ryan Conwell", team: "Louisville" },
      { name: "Silas Demary Jr.", team: "UConn" },
      { name: "Zuby Ejiofor", team: "St. Johns" },
      { name: "Robert Wright III", team: "BYU" },
      { name: "Mikey Lewis", team: "St. Marys" },
      { name: "Sam Lewis", team: "Virginia" },
      { name: "Trent Perry", team: "UCLA" },
      { name: "Dominique Daniels Jr.", team: "CA Baptist" },
      { name: "Cruz Davis", team: "Hofstra" },
    ],
  },
  {
    real_name: "Alex",
    team_name: "Alex's Team",
    players: [
      { name: "Koa Peat", team: "Arizona" },
      { name: "Braden Smith", team: "Purdue" },
      { name: "Aday Mara", team: "Michigan" },
      { name: "Braylon Mullins", team: "UConn" },
      { name: "Eliott Cadeau", team: "Michigan" },
      { name: "Nate Ament", team: "Tennessee" },
      { name: "Malik Reanu", team: "Miami" },
      { name: "Donovan Dent", team: "UCLA" },
      { name: "Peter Sudar", team: "Miami OH" },
      { name: "Tyler Biladou", team: "UCLA" },
      { name: "Jaron Pierre", team: "SMU" },
      { name: "JP Estrella", team: "Tennessee" },
    ],
  },
  {
    real_name: "Zeth Hearld",
    team_name: "Zeth's Team",
    players: [
      { name: "Darius Acuff", team: "Arkansas" },
      { name: "Emanuel Sharp", team: "Houston" },
      { name: "Nick Boyd", team: "Wisconsin" },
      { name: "Ja'Kobi Gillespie", team: "Tennessee" },
      { name: "Bennett Stirtz", team: "Iowa" },
      { name: "Tre Donaldson", team: "Miami" },
      { name: "Seth Trimble", team: "North Carolina" },
      { name: "Nimari Burnett", team: "Michigan" },
      { name: "Tomislav Ivisic", team: "Illinois" },
      { name: "Mark Mitchell", team: "Missouri" },
      { name: "Izaiyah Nelson", team: "South Florida" },
      { name: "Terrence Hill Jr.", team: "VCU" },
    ],
  },
  {
    real_name: "Nick",
    team_name: "Nick's Team",
    players: [
      { name: "Isaiah Evans", team: "Duke" },
      { name: "Morez Johnson Jr.", team: "Michigan" },
      { name: "Rueben Chinyelu", team: "Florida" },
      { name: "Ivan Kharchenkov", team: "Arizona" },
      { name: "Urban Klavzar", team: "Florida" },
      { name: "Trey McKenney", team: "Michigan" },
      { name: "Trevon Brazile", team: "Arkansas" },
      { name: "Chris Cenac Jr.", team: "Houston" },
      { name: "Tyon Grant-Foster", team: "Gonzaga" },
      { name: "Killyan Toure", team: "Iowa State" },
      { name: "Malique Ewin", team: "Arkansas" },
      { name: "Riley Kugel", team: "UCF" },
    ],
  },
  {
    real_name: "Dan",
    team_name: "HanoverEZ",
    players: [
      { name: "Jaden Bradley", team: "Idaho" },
      { name: "Alex Condon", team: "Florida" },
      { name: "Motiejus Krivas", team: "Arizona" },
      { name: "Alex Karaban", team: "UConn" },
      { name: "Oscar Cluff", team: "Purdue" },
      { name: "Flory Bidunga", team: "Kansas" },
      { name: "Cayden Boozer", team: "Duke" },
      { name: "Dame Sarr", team: "Duke" },
      { name: "MJ Collins Jr.", team: "Utah" },
      { name: "Braden Frager", team: "Nebraska" },
      { name: "J'Vonne Hadley", team: "Louisville" },
      { name: "Isaiah Brown", team: "Florida" },
    ],
  },
  {
    real_name: "RJ Armstrong",
    team_name: "Hoops, There it is",
    players: [
      { name: "Joshua Jefferson", team: "Iowa State" },
      { name: "Keaton Wagler", team: "Illinois" },
      { name: "Tarris Reed Jr.", team: "UConn" },
      { name: "Thijs De Ridder", team: "Virginia" },
      { name: "David Mirkovic", team: "Illinois" },
      { name: "Tre White", team: "Kansas" },
      { name: "Latrell Wrightsell", team: "Alabama" },
      { name: "Rienk Mast", team: "Nebraska" },
      { name: "Jacari White", team: "Virginia" },
      { name: "Jamarques Lawrence", team: "Nebraska" },
      { name: "Mario Saint-Supery", team: "Gonzaga" },
      { name: "Jamarion Batemon", team: "Iowa State" },
    ],
  },
  {
    real_name: "Dave",
    team_name: "Dave's Team",
    players: [
      { name: "Kingston Fleming", team: "Houston" },
      { name: "Labaron Philon", team: "Alabama" },
      { name: "Pryce Sandfort", team: "Nebraska" },
      { name: "Tyler Tanner", team: "Vanderbilt" },
      { name: "Bruce Thornton", team: "Ohio State" },
      { name: "Otega Oweh", team: "Kentucky" },
      { name: "Dailyn Swain", team: "Texas" },
      { name: "Carson Cooper", team: "Michigan State" },
      { name: "Rashaun Agee", team: "Texas A&M" },
      { name: "Matas Vokietaitis", team: "Texas" },
      { name: "Wes Enis", team: "South Florida" },
      { name: "Jayden Stone", team: "Missouri" },
    ],
  },
];
